
FROM node:8.16.2-stretch

WORKDIR /var/app

# COPY package.json .
# RUN npm install --quiet
# COPY . .

# CMD sh /var/app/containers/npm_build/entrypoint.sh

CMD sh app/containers/npm_build/entrypoint.sh

# CMD pwd && ls -l && ls -l /var/app && ls -l /var/app/containers && ls -l /var/app/containers/npm_build
